### ISSUE TITLE
Release:1.2 Cmake fails.

### ISSUE THREAD

**Issue by LCWilliams** [JosephP91/curlcpp#127]
Following instructions:  made a "build" directory.  Cd into it.  `cmake ..`, and get greeted by this:

```
-- IPO / LTO supported, will enable for targets in release build type
You have called ADD_LIBRARY for library curlcpp without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error: Could not open file for write in copy operation /curlcppConfig.cmake.tmp
CMake Error: : System Error: Permission denied
CMake Error at CMakeLists.txt:37 (configure_file):
  configure_file Problem configuring file


-- Configuring incomplete, errors occurred!
```

Running on Linux Mint 19 | Cmake: 3.10.2

Testing release 1.1: and cmake runs fine.

**Comment by JosephP91** [comment]
@Xeverous hi, any clue of what is happening after last changes?

**Comment by Xeverous** [comment]
My fault, compare

https://cmake.org/cmake/help/v3.10/command/add_library.html

vs

https://cmake.org/cmake/help/v3.11/command/add_library.html

The minimum version required should be 3.11. Only this and later versions allow a fully source-less target creation and then `target_sources` calls.

**Comment by JosephP91** [comment]
Ok, so updating the minimum required cmake version should fix the problem, right?

**Comment by Xeverous** [comment]
Right.

**Comment by JosephP91** [comment]
@LCWilliams can you please try now? I have updated the minimum required version from 3.10 to 3.11

**Comment by LCWilliams** [comment]
> @LCWilliams can you please try now? I have updated the minimum required version from 3.10 to 3.11

One moment! :P  just crawled out of bed!

**Comment by LCWilliams** [comment]
Still broken; Updated Cmake to latest (3.17) and still get the **exact** error as in OP.
I'm too unfamiliar with Cmake myself to really go digging at this. D:

**Comment by JosephP91** [comment]
mmm ok. Are you encountering the same error or is it different? If so, can you post the entire error?

**Comment by LCWilliams** [comment]
If it helps, when viewing `CmakeLists.txt` : `CURLCPP_BINARY_DIR` is the **only** variable to be blue; all other capitalised variables are green.

It's the same error.  I had just slightly moved the text around when first debugging this hence the 1 line difference I thought meant something. :stuck_out_tongue:

**Comment by JosephP91** [comment]
We invoke the Jedi Master of CMake @Xeverous

**Comment by LCWilliams** [comment]
Ah, I stand corrected: it's the same error: MINUS the problem about using `ADD LIBRARY`.  Sorry, being a derp.

**Comment by LCWilliams** [comment]
Okay; no idea what it's potentially done in the backend, but I modified the last command in CmakeLists.txt to this:

```configure_file(CMake/curlcppConfig.cmake.in
  ${CMAKE_CURRENT_BINARY_DIR}/curlcppConfig.cmake @ONLY)``` 
 and it works~

**Comment by Xeverous** [comment]
The add library error is gone which is good news, but for:

```
CMake Error: Could not open file for write in copy operation /curlcppConfig.cmake.tmp
CMake Error: : System Error: Permission denied
```
it means there are 2 possible issues:

- you actually have no permissions to do this operation
- directory does not exist

Usually it's the latter. The path that CMake outputs is the full path. So `/curlcppConfig.cmake.tmp` simply means that `CURLCPP_BINARY_DIR` was empty. I haven't found any presence of this variable so it should be replaced with CMake built-ins. `${CMAKE_CURRENT_BINARY_DIR}/lib/cmake/curlcpp` or `${CMAKE_BINARY_DIR}/lib/cmake/curlcpp`. Would need to check which one is more correct but any way, all well-known libraries that I use put their cmake config files into `CMAKE_INSTALL_PREFIX/lib/cmake/<project_name>`.

**Comment by strangePo** [comment]
Sorry for reopening this issue bit for it's still not working.
I'm using cmake 3.16 (also tried 3.13-3.15) using the ExternalProject plugin and FetchContent.

Relevant CMakeLists.txt lines:

```
FetchContent_Declare(
	curlcpp
	GIT_REPOSITORY https://github.com/JosephP91/curlcpp.git
  	GIT_TAG        1.4
)

FetchContent_GetProperties(curlcpp)
if(NOT curlcpp_POPULATED)
	FetchContent_Populate(curlcpp)
	message("curlcpp source dir: ${curlcpp_SOURCE_DIR}")
	message("curlcpp binary dir: ${curlcpp_BINARY_DIR}")
	add_subdirectory(${curlcpp_SOURCE_DIR} ${curlcpp_BINARY_DIR})
endif()
```

Result

```
curlcpp source dir: /home/user/project/build/linux/Debug/_deps/curlcpp-src
curlcpp binary dir: /home/user/project/build/linux/Debug/_deps/curlcpp-build
-- IPO / LTO supported, will enable for targets in release build type
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found suitable version "7.68.0", minimum required is "7.28.0")  
CMake Error: Could not open file for write in copy operation /usr/local/lib/curlcpp/curlcppConfig.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at build/linux/Debug/_deps/curlcpp-src/CMakeLists.txt:40 (configure_file):
  configure_file Problem configuring file
```

So apparently it tries to write to **/usr/local/lib/** which is a bad Idea.

**Comment by strangePo** [comment]
I changed FetchContent to patch the CMakeLists.txt on the fly which makes it work again.

```
FetchContent_Declare(
	curlcpp
	GIT_REPOSITORY https://github.com/JosephP91/curlcpp.git
  	GIT_TAG        1.4
  	PATCH_COMMAND patch -p1 < ${CMAKE_CURRENT_SOURCE_DIR}/curlcpp_cmake.patch
)
```

curlcpp_cmake.patch:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6f17593..856b401 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -38,4 +38,4 @@ add_subdirectory(test)
 set(CURLCPP_LIB_LOCATION "$<TARGET_FILE:${curlcpp}>")
 
 configure_file(CMake/curlcppConfig.cmake.in
-  ${CMAKE_INSTALL_PREFIX}/lib/curlcpp/curlcppConfig.cmake @ONLY)
+  ${CMAKE_CURRENT_BINARY_DIR}/curlcppConfig.cmake @ONLY)
```
